### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rukshn**
The live example link is not working in the README.md file, the website seems to be out of service. 

Updated the live example link with CodeSandbox link https://codesandbox.io/s/xenodochial-river-77mqey

### CODE REVIEW

**Comment by mcmire** [comment]
Thanks for the contribution. I think since we don't own this CodeSandbox project, it could be seen as a suspicious link, so I'm hesitant to merge this. It would be better if we could figure out some way to automatically generate a CodeSandbox project. Maybe we can pass code through query parameters? If that's not possible then we should probably create one ourselves just so it's a little more official.

**Comment by rukshn** [comment]
@mcmire you can fork the code sandbox project (there is a button to fork) to the official codesandbox account of Metamask and can use that link to replace mine instead

Will that do?

**Comment by rukshn** [comment]
@mcmire if you're happy we can use this CodePen link instead - https://codepen.io/pen/ZErxYZm

**Comment by windymelt** [comment]
We can remove broken link anyway.

**Comment by rukshn** [comment]
@windymelt Can't we replace the broken link with the example codepen link I provided?

**Comment by mcmire** [comment]
Hi @rukshn, thanks so much for taking the initiative to update the README. We've just published a demo page using GitHub Pages and updated the README to feature the correct link to that page. So we shouldn't have a broken link going forward. Thanks again!

**Pull request closed without merging**
