### PR TITLE
Add a way to generate demo page

### PR DESCRIPTION
**Pull request by mcmire**
Add a `build-demo` script which will build the demo page to the `demo-build/` directory. This directory can then be copied to a `gh-pages` branch so that we can publish the demo page to GitHub Pages.

Also, considering that we also need an HTML file to build the demo page, move that along with the JavaScript file to the `demo/` directory.

### CODE REVIEW

**Review by danfinlay — APPROVED** [review]
Yup, this looks like it should work to me! Should let it all work on gh-pages too! Should we check a build in, or maybe use a proper gh-deploy type script?

**Comment by mcmire** [comment]
@danfinlay I would love to use our [GH Pages action](https://github.com/MetaMask/action-publish-gh-pages), but it assumes that the project uses Yarn, which this one does not (yet). It may be an easy fix to make that work, but I wasn't sure. I figure we can just manually push to `gh-pages` for now until I can get that set up. But that would be a next logical step to automate redeploying to GH Pages when a new commit is added to `master`.

**Comment by danfinlay** [comment]
yeah, we update this so infrequently that I don’t think it’s terrible to just heard code a build

**Review by cryptodev-2s — COMMENTED** [review]
LGTM!

**Review by cryptodev-2s — APPROVED** [review]

**Pull request merged**
